### ISSUE TITLE
This package requires ZFS version 0.8 or later - help

### ISSUE THREAD

**Issue by mwoffenden** [45Drives/cockpit-zfs-manager#6]
Installed on Ubuntu 20.04.3 LTS  and Cockpit Version 215 using these commands

> git clone https://github.com/optimans/cockpit-zfs-manager.git
> sudo cp -r cockpit-zfs-manager/zfs /usr/share/cockpit

When I try to run it from cockpit I see:

> This package requires ZFS version 0.8 or later
> If ZFS is installed, check the module is loaded into the kernel.

What am I doing wrong?

**Comment by dawsondellavalle** [comment]
Hi there,

We must have missed that and need to update the instructions. You can use the below clone command to get our version of the zfs manager.

```
git clone https://github.com/45Drives/cockpit-zfs-manager.git
```

Kind regards,
Dawson Della Valle
